site_name: 开源操作系统社区

theme:
  name: material
  logo: https://os2edu.cn/assets/images/logo.png
  favicon: https://os2edu.cn/assets/images/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    # - navigation.
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra:
  homepage: https://os2edu.cn

nav:
  - 主页: index.md
  - Page 1: page1/index.md
  - Page n: section/page-n.md

plugins:
  - search
  - glightbox
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true

repo_url: https://github.com/DongJianHao123/mkdocs-test.git
repo_name: Dongjianhao123/mkdocs-test
